apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wallet-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wallet
    spec:
      containers:
      - name: wallet
        image: alexec/wallet:1.0.0.
        ports:
        - containerPort: 8080