---
apiVersion: v1
kind: Service
metadata:
  name: wallet
  labels:
    app: wallet
spec:
  ports:
  - port: 8080
    name: wallet
  selector:
    app: wallet
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wallet-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wallet
    spec:
      containers:
      - name: wallet
        image: alexec/wallet:1.0.0
        env:
          - name: JAVA_OPTS
            value: -Xmx64m
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://walletdb:5432/wallet
          - name: SPRING_DATASOURCE_USERNAME
            value: wallet
          - name: SPRING_DATASOURCE_PASSWORD
            value: wallet
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /0
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 3
