version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: "circleci/openjdk:8"
      - image: "circleci/postgres:9-alpine"
    steps:
      - checkout
      - restore_cache:
          key: maven-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_test_results:
          path: target/failsafe-reports
      - setup_remote_docker
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build --rm=false -t alexec/wallet:$CIRCLE_SHA1 .
      - run: docker push alexec/wallet
      - run: ./deploy.sh
